repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
#- repo: https://github.com/jumanjihouse/pre-commit-hooks
#  rev: 2.1.5
#  hooks:
#    - id: rubocop

# Alternatively, replace/add .git/hooks/pre-commit with the following code:

#!/bin/bash
#files=$(git status -s | grep -E 'A|M' | awk '{print $2}')
#files="$files $(git status -s | grep -E 'R' | awk '{print $4}')"
#echo $files | xargs rubocop --display-cop-names --extra-details --parallel --force-exclusion
