# MySQL Configuration used for Autolab Docker Deployments
production:
  adapter: mysql2
  database: autolab_development
  pool: 5
  username: <MYSQL_USERNAME>
  password: <MYSQL_PASSWORD>
  socket: /var/run/mysqld/mysqld.sock
  host: mysql
  variables:
    sql_mode: NO_ENGINE_SUBSTITUTION
